name: "Monitor API server"
description: "Monitor the target API server and sync the latest version with the fake server if it has any change."
author: "Bryant Liu"
inputs:
  config-path:
    description: "The file path of the PyFake-API-Server-Surveillance configuration."
    required: false
    default: "./fake-api-server-surveillance.yaml"
runs:
  using: "composite"
  steps:
    - name: Fail-fast in unsupported environments
      if: runner.os == 'Windows'
      shell: bash -eEuo pipefail {0}
      run: |
        >&2 echo This action is only able to run under GNU/Linux or Apple MacOS environments
        exit 1

    - name: Clone project
      uses: actions/checkout@v5
      with:
        repository: 'Chisanan232/PyFake-API-Server-Surveillance'
        ref: 'master'

    - name: Install Python 3.12 for running surveillance
      uses: actions/setup-python@v6
      with:
        python-version: '3.12'

    - name: Install Python dependencies
      shell: bash
      run: |
        pip --version
        pip install -U poetry

    - name: Build Python runtime environment by Poetry
      shell: bash
      run: |
        poetry --version
        poetry install

    - name: Run surveillance
      run: poetry run run-fake-server-surveillance
#      run: poetry run fake rest-server run-surveillance
      shell: bash
      env:
        CONFIG_PATH: ${{ inputs.config-path }}
branding:
  icon: 'monitor'
  color: 'black'
