site_name: Fake-API-Server-Surveillance
site_url: https://chisanan232.github.io/pyfake-api-server-surveillance/
site_author: Bryant Liu
site_description: >-
  Mock your API server, e.g., HTTP API server, by YAML configuration and set up an application in minutes

# Repository
repo_name: Chisanan232/PyFake-API-Server-Surveillance
repo_url: https://github.com/Chisanan232/PyFake-API-Server-Surveillance

# Copyright
copyright: Copyright &copy; 2025 Bryant Liu
#copyright: Copyright &copy; 2025 - 2026 Bryant Liu

theme:
  name: material
#  custom_dir: ./docs/_overrides
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
#  favicon: assets/favicon.png
  icon:
    logo: logo

# Plugins
plugins:
  # Doc as Code
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: sphinx
            docstring_section_style: spacy
            docstring_options:
              ignore_init_summary: true
            merge_init_into_class: true
            relative_crossrefs: true
  # Versioning documentation
  - mike:
      alias_type: symlink
      redirect_template: null
      deploy_prefix: ''
      canonical_version: null
      version_selector: true
      css_dir: css
      javascript_dir: js
  # Documentation modification info - create & update time
  - git-revision-date-localized:
      type: timeago
#      custom_format: "%d. %B %Y"
      timezone: Asia/Taipei
#      locale: en
      fallback_to_build_date: false
      enable_creation_date: true
#      exclude:
#          - index.md
      enable_git_follow: true
      enabled: true
      strict: true
  # Documentation modification info - contributor
  - git-committers:
      repository: Chisanan232/PyFake-API-Server-Surveillance
      branch: master

# Additional configuration
extra:
  # Versioning documentation
  version:
    provider: mike
    default: stable
    alias: true
  # Documentation analytics
  analytics:
    provider: google
    property: G-G1YK8C9EE4
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback!
  # Social info
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Chisanan232
#    - icon: fontawesome/brands/docker
#      link: https://hub.docker.com/repository/docker/chisanan232/pyfake-api-server
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/fake-api-server-surveillance/

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - Home: index.md
  - Getting started:
    - Version requirements: getting-started/version-requirements.md
    - Installation: getting-started/installation.md
    - Configure surveillance: getting-started/configure-surveillance.md
    - Set up your surveillance: getting-started/setup-surveillance.md
  - Configure references:
    - Basic info: configure-references/config-basic-info.md
    - Fake API Server: configure-references/fake-api-server.md
    - Git info: configure-references/git-info.md
    - GitHub info: configure-references/github-info.md
  - Development:
    - development/index.md
    - How it works: development/how-it-works.md
    - Software architecture: development/software-architecture.md
    - Contributing : development/contributing.md
  - Release notes:
    - release_note/index.md
    - Version 0.X.X: release_note/version_0xx.md
