def run() -> None:
    # get the API doc config from end point (request API doc config and get response)
    # check the diff between local config and the new config (check the diff by git?)
    # if no diff = nothing, else it would update the config (commit the change and request PR by git and gh?)
    print("monitor the github repro ...")
    # result = Surveillance.monitor()
    print("got difference~")
    # GitHelper.commit_change()
    print("notify developers")
    # Notificatier.notidy()
