name: Request a feature or change
description: Have some idea for PyMock-Server? Welcome to request a feature or change
labels: ["🔍 enhancement"]
body:

  - type: textarea
    id: description
    attributes:
      label: Description
      description: >-
        Please explain your idea as short as possible so that we could fully
        understand what feature, change or improvement you're proposing.
    validations:
      required: true

  - type: textarea
    id: use-cases
    attributes:
      label: Use cases
      description: >-
        Please explain how it works or how we should use it by your idea.
    validations:
      required: true
